FROM microsoft/dotnet:1.0.5-sdk
MAINTAINER Mateusz Probachta <mateusz.probachta@gmail.com>

RUN mkdir -p /app
ADD . /src

EXPOSE 5000/tcp
ENV ASPNETCORE_URLS http://*:5000
ENV ASPNETCORE_ENVIRONMENT=Development

WORKDIR /app
