version: "2"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./src:/app
    links:
      - db
    ports:
      - "5000:5000"
    command: bash -c "dotnet restore; dotnet watch run"

  db:
    image: microsoft/mssql-server-linux:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=qsddF234fdfFFsx
