version: "2"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./src:/app
    links:
      - db
    ports:
      - "5000:5000"
    command: bash -c "dotnet restore; dotnet watch run"

  db:
    build:
      context: .
      dockerfile: ./Dockerfile.mssql
    volumes:
      - ./src/sql:/app
